config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root      'static_pages#home'
  post      '/static_pages/guest_sign_in', to: 'static_pages#guest_sign_in'
  get       '/login',  to: 'sessions#new'
  post      '/login',  to: 'sessions#create'
  delete    '/logout', to: 'sessions#destroy'
  get       '/signup', to: 'users#new'
  post      '/signup', to: 'users#create'
  post      '/add_item',        to: 'carts#add_item'
  post      '/change_quantity', to: 'carts#change_quantity'
  delete    '/delete_item',     to: 'carts#destroy'

  resources :products
  resources :users
  resources :orders
  resources :carts

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = session[:cart] || []
  end

  def add_item
    session[:cart] = [] if session[:cart].nil?

    if index_of_added_item.nil?
      session[:cart].push(added_item)
    else
      session[:cart][index_of_added_item]["quantity"] += params[:quantity].to_i
    end

    redirect_to carts_path
  end

  def change_quantity
    session[:cart][index_of_added_item]["quantity"] = params[:quantity].to_i
    redirect_to carts_path
  end

  def destroy
    session[:cart].delete_at(index_of_added_item)
    redirect_to carts_path
  end

  private

    def index_of_added_item
      indexes = session[:cart].each_index.select {|i| session[:cart][i]["product_id"] == params[:product_id].to_i }
      indexes[0]
    end

    def added_item
      { product_id: params[:product_id].to_i, quantity: params[:quantity].to_i }
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  def get_product_name(product_id)
    Product.find_by(id: product_id).product_name
  end

  def get_category_name(product_id)
    Product.find_by(id: product_id).category.category_name
  end

  def get_price(product_id)
    Product.find_by(id: product_id).price
  end

  def get_sub_total(item)
    get_price(item["product_id"]) * item["quantity"]
  end

  def get_total(cart)
    cart.sum {get_sub_total(_1)}
  end
end

app/views/carts/index.html.erb
<% provide(:title, "カート") %>

<main>

  <% if @cart.present? %>
    <div class="container">
      <div class="row">
        <div class="col-12 card border-dark mt-5">
          <div class="cord-body ml-3 mb-2">
            <h4 class="mt-4">お届け先</h4>
            <p class="mb-2" style="padding-left: 20px;">
              <%= "〒#{current_user.zipcode[0..2]}-#{current_user.zipcode[3..6]}" %>
              <%= "#{current_user.prefecture}#{current_user.municipality}#{current_user.address}#{current_user.apartments}" %>
            </p>
            <p style="padding-left: 160px;">
              <%= "#{current_user.last_name} #{current_user.first_name}様"%>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <table class="table mt-5 ml-3 border-dark">
          <thead>
            <tr class="text-center">
              <th class="border-bottom border-dark" style="width:13%;">
                No
              </th>
              <th class="border-bottom border-dark" style="width:18%;">
                商品名
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                商品カテゴリ
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                値段
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                個数
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                小計
              </th>
            </tr>
          </thead>
          <tbody>
            <% @cart.each.with_index(1) do |item,i| %>
              <tr class="text-center">
                <th class="align-middle">
                  <%= i %>
                </th>
                <td class="align-middle">
                  <%= get_product_name(item["product_id"]) %>
                </td>
                <td class="align-middle">
                  <%= get_category_name(item["product_id"]) %>
                </td>
                <td class="align-middle">
                  <%= "#{get_price(item["product_id"])}円" %>
                </td>
                <td class="align-middle">
                  <%= form_with(url: change_quantity_path, local: true) do |f| %>
                    <%= hidden_field_tag :product_id, item["product_id"] %>
                    <%= f.number_field :quantity, value:item["quantity"], min: 1, max:999, required:true %>&nbsp;&nbsp;個
                    <%= f.submit "更新", class: 'btn btn-light' %>
                  <% end %>
                </td>
                <td class="align-middle">
                  <%= "#{get_sub_total(item)}円" %>
                </td>
                <td class="border-0 align-middle">
                  <%= link_to "削除", delete_item_path(item) ,  method: :delete, class:"btn btn-danger"%>
                </td>
              </tr>
            <% end %>
            <tr class="text-center">
              <th class="border-bottom-0 align-middle">
              </th>
              <td class="border-bottom-0 align-middle">
              </td>
              <td class="border-bottom-0 align-middle">
              </td>
              <td class="border-bottom-0 align-middle">
              </td>
              <td class="border-bottom-0 align-middle">
                合計
              </td>
              <td class="border-bottom-0 align-middle">
                <%= "#{get_total(@cart)}円" %>
              </td>
            </tr>
            <tr class="text-right">
              <th class="border-0">
              </th>
              <td class="border-0">
                <%= button_to "買い物を続ける", products_path , method: :get, class:"btn btn-success"%>
              </td>
              <td class="border-0">
              </td>
              <td class="border-0">
              </td>
              <td class="border-0">
                <%= button_to "注文を確定する", orders_path , method: :post ,class:"btn btn-primary"%>
              </td>
              <td class="border-0 align-middle">
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  <% else %>

    <div class="blockquote mt-5 text-center">
      <h1 style="font-weight: bolder">カートに商品はありません</h1>
    </div>

  <% end %>


</main>