config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root      'static_pages#home'
  post      '/static_pages/guest_sign_in', to: 'static_pages#guest_sign_in'
  get       '/login',  to: 'sessions#new'
  post      '/login',  to: 'sessions#create'
  delete    '/logout', to: 'sessions#destroy'
  get       '/signup', to: 'users#new'
  post      '/signup', to: 'users#create'
  post      '/add_item',        to: 'carts#add_item'
  post      '/change_quantity', to: 'carts#change_quantity'
  delete    '/delete_item',     to: 'carts#destroy'

  resources :products
  resources :users
  resources :orders
  resources :carts

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :purchases, dependent: :destroy
  belongs_to :category
  belongs_to :sale_status
  belongs_to :product_status
  belongs_to :user

  def self.search(keyword, category_id)
    where("product_name LIKE(?)", "%#{keyword}%").where(category_id: category_id.to_s)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:keyword].present? && params[:category_id].present?
      @products = Product.search(params[:keyword], params[:category_id]).page(params[:page]).per(15)
      @keyword = params[:keyword]

      render "index"
    else
      @products = Product.all.order("created_at ASC").page(params[:page]).per(15)
    end
  end

  def show
    @product = Product.find_by(id: params[:id])
  end
end

app/views/products/index.html.erb
<% provide(:title, "商品検索") %>

<main>
  <% if @products.present? %>
    <%= form_with url: products_path, method: :get, local: true do |form| %>
    <div class="mt-5 mx-auto" style="width: 200px">
      <h2>商品検索画面</h2>
    </div>
    <div class="container mt-5">
      <div class="mx-auto row">
        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">商品名</label>
        <div class="col-sm-6">
          <%= form.text_field :keyword, value: @keyword, class: "form-control form-control-lg", id: "colFormLabelLg", required: true %>
        </div>
        <div class="col-sm-4 mt-1">
          <%= form.submit '検索', class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="mx-auto row">
        <label class="col-sm-2 col-form-label col-form-label-lg" for="exampleFormControlSelect2">商品カテゴリ</label>
        <div class="col-sm-4">
          <%= form.collection_select :category_id, Category.all, :id, :category_name, {include_blank: "選択して下さい" }, {class: "form-control"}  %>
        </div>
      </div>
    </div>
    <div class="container">
      <p><%= "全#{@products.total_count}件" %></p>
      <table class="table table-hover product-table" border="1" style="border-collapse: collapse">
        <thead>
          <tr class="table-header">
            <th class="text-left" width="55%">
              商品名
            </th>
            <th class="text-center" width="15%">
              商品カテゴリ
            </th>
            <th class="text-center" width="15%">
              価格
            </th>
            <th class="text-center" width="15%"></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td scope="row">
                <%= product.product_name %>
              </td>
              <td class="text-center">
                <%= product.category.category_name %>
              </td>
              <td class="text-center">
                <%= "#{product.price}円" %>
              </td>
              <td class="text-center">
                <%= link_to "商品詳細", product_path(product) , class:"btn btn-primary btn-sm"%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="container">
      <nav aria-label="...">
        <ul class="pagination justify-content-center">
          <%= paginate @products %>
        </ul>
      </nav>
    </div>
    <% end %>
  <% else %>
    <div class="container">
      <div class="mt-5 text-center">
        <h1>該当商品が見つかりませんでした…</h1>
        <p class="mt-5">商品検索画面に戻り、やり直してください</p>
        <%= link_to "商品検索画面へ", products_path, type: "button", class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</main>

app/views/products/show.html.erb
<% provide(:title, "商品詳細") %>

  <main>
    <% if @product.present? %>
      <div class="container">
        <div class="mt-5 jumbotron bg-white">
          <h1 class="text-center"><%= @product.product_name %></h1>
          <h2 class="text-center">商品<%= @product.id%></h2>
          <div class="offset-sm-3">
            <p class="offset-sm-6"><%= @product.category.category_name %></p>
            <p><%= @product.description %></p>
            <p>探求学園Rails専攻限定商品！</p>
            <p class="mt-4 mb-5"><%= @product.price %></p>
          </div>

          <%= form_with(url: add_item_path, local: true) do |f| %>

            <div class="row justify-content-center">
              <%= f.label :購入個数, class:'mt-1 col-sm-1' %>
              <div class="col-sm-1">
                <%= f.number_field :quantity, class:'form-control',  min: 1, max:999, required:true %>
              </div>
              <%= f.label :個, class:'mt-1 col-sm-1' %>

              <%= f.text_field :product_id ,value:@product.id  ,hidden:true %>

              <div class="col-sm-2">
                <%= f.submit "カートへ", class: 'btn btn-primary btn-block' %>
              </div>
            </div>

          <% end %>

        </div>
      </div>
    <% else %>
      <div class="container">
        <div class="mt-5 text-center">
          <h1>該当商品が見つかりませんでした…</h1>
          <p class="mt-5">商品検索画面に戻り、やり直してください</p>
          <%= link_to "商品検索画面へ", products_path, type: "button", class: "btn btn-primary" %>
        </div>
      </div>
      </div>
    <% end %>
  </main>