config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root      'static_pages#home'
  post      '/static_pages/guest_sign_in', to: 'static_pages#guest_sign_in'
  get       '/login',  to: 'sessions#new'
  post      '/login',  to: 'sessions#create'
  delete    '/logout', to: 'sessions#destroy'
  get       '/signup', to: 'users#new'
  post      '/signup', to: 'users#create'
  post      '/add_item',        to: 'carts#add_item'
  post      '/change_quantity', to: 'carts#change_quantity'
  delete    '/delete_item',     to: 'carts#destroy'

  resources :products
  resources :users
  resources :orders
  resources :carts

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/views/layouts/_footer.html.erb
<footer>
    <h1>探求学園Rails専攻</h1>
    <p>© 2020 QuestAcademia, All rights reserved</p>
</footer>

app/views/layouts/_head.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header>
  <% if logged_in? %>

    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <div class="navbar-nav me-auto">
          <h1><%= link_to "探求学園Rails専攻", root_path ,class:"nav-link navbar-brand"%></h1>
        </div>
        <div>
          <ul>
            <p><%= "#{@current_user.last_name} #{@current_user.first_name}さん"%></p>
         </ul>
          <ul class="navbar-nav">
            <%= link_to "商品検索", products_path ,class:"nav-link text-dark"%>
            <%= link_to "カート", carts_path ,class:"nav-link text-dark"%>
            <%= link_to "注文履歴", orders_path ,class:"nav-link text-dark"%>
            <%= link_to "ユーザ情報", user_path(@current_user) ,class:"nav-link text-dark"%>
            <%= link_to "ログアウト", logout_path , method: :delete ,class:"nav-link text-dark"%>
          </ul>
        </div>
      </div>
    </nav>

  <% else %>

    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <div class="navbar-nav mr-auto">
          <h1><%= link_to "探求学園Rails専攻", root_path ,class:"nav-link navbar-brand"%></h1>
        </div>
        <div>
          <ul>
            <li>
              <li><%= link_to "ログイン", login_path ,class:"text-dark" %></li>
              <li><%= link_to "新規登録", signup_path ,class:"text-dark" %></li>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>